prx_models/MushrObservation current_observation
geometry_msgs/Pose2D goal_configuration
std_msgs/Duration planning_duration
std_msgs/Duration execution_duration
---
ml4kp_bridge/Plan output_plan
uint8 TYPE_SUCCESS=1
uint8 TYPE_FAILURE=0
uint8 planner_output