uint64 idx
ml4kp_bridge/SpacePoint current_observation
geometry_msgs/Pose2D goal_configuration
std_msgs/Duration planning_duration
---
ml4kp_bridge/PlanStamped output_plan
ml4kp_bridge/TrajectoryStamped output_trajectory
prx_models/Tree sln_tree
uint8 TYPE_SUCCESS=1
uint8 TYPE_FAILURE=0
uint8 planner_output