name: "LTV_CSBRM"
path: "LTV_CSBRM"

state_space:
  lower_bound: [-100, -100, -10, -10]
  upper_bound: [100, 100, 10, 10]

control_space:
  lower_bound: [-10,-10]
  upper_bound: [ 10, 10]


vis_body: "body"