# Find ID of camera:
#      $ v4l2-ctl --device=/dev/videoN --all | grep Serial

# id: "0"
camera_id: "96214279"
camera_name: "logitech_96214279"
camera: "/dev/video6"
height: 1080 
width: 1920
frequency: 50
display_video: true

fx: &fx 1.1993e+03
fy: &fy 1.1992e+03

cx: &cx 989.4715
cy: &cy 566.5739

skew: &skew 3.8743

# camera_matrix: [1.10856930e+03, 0.0, 9.49330984e+02, 0, 1.10897817e+03, 5.74566862e+02]

camera_matrix: [*fx, *skew, *cx, 0, *fy, *cy, 0, 0, 1]
dist_coeffs: [0.0510, -0.1293, 0.0, 0.0, 0.0]

pose:
  quaternion: [0.0, 0.0, -1.0, 0.0] # w first
  position: [-0.5, -1.0, 2.0]