topics:
  - name: "/GT/cells"
    type: "visualization_msgs::MarkerArray"
  - name: "/GT/collision"
    type: "std_msgs::Bool"
  - name: "/GT/collisions/marker"
    type: "visualization_msgs::Marker"
  - name: "/GT/trajectories/marker"
    type: "visualization_msgs::Marker"
  - name: "/environment_marker_array"
    type: "visualization_msgs::MarkerArray"
  - name: "/gotube/balls"
    type: "visualization_msgs::MarkerArray"
  - name: "/gotube/trajectories/center/marker"
    type: "visualization_msgs::Marker"
  - name: "/gotube/trajectories/marker"
    type: "visualization_msgs::Marker"
  - name: "/mg/collision"
    type: "std_msgs::Bool"
  - name: "/mg/cubes/balls"
    type: "visualization_msgs::MarkerArray"
  - name: "/mg/cubes/lie_algebra"
    type: "visualization_msgs::Marker"
  - name: "/mg/cubes/state_space"
    type: "visualization_msgs::Marker"
  - name: "/mg/trajectories/marker"
    type: "visualization_msgs::Marker"
  - name: "/mg/trajectories/nominal/marker" 
    type: "visualization_msgs::Marker"
  - name: "/mushr/state"
    type: "ml4kp_bridge::SpacePointStamped"
  - name: "/mushr/state/marker"
    type: "visualization_msgs::Marker"
  - name: "/randup/collision"
    type: "std_msgs::Bool"
  - name: "/randup/collisions/marker"
    type: "visualization_msgs::Marker"
  - name: "/randup/convex_hull"
    type: "visualization_msgs::MarkerArray"
  - name: "/randup/trajectories/marker"
    type: "visualization_msgs::Marker"
  - name: "/safety/input/cov_w"
    type: "ml4kp_bridge::SpacePoint"
  - name: "/safety/input/cov_x0"
    type: "ml4kp_bridge::SpacePoint"
  - name: "/safety/input/plan"
    type: "ml4kp_bridge::PlanStepStampedArray"
  - name: "/safety/input/randup/total_time"
    type: "std_msgs::Duration"
  - name: "/safety/input/randup/total_trajs"
    type: "std_msgs::Int32"
  - name: "/mg/trajectories/start_states/marker"
    type: "visualization_msgs::Marker"
  - name: "/mg/x0/noise"
    type: "visualization_msgs::Marker"
  # - name: "/mushr/vesc/commands/motor/duty_cycle"
  #   type: "std_msgs::Float64"
  # - name: "/mushr/vesc/commands/motor/position"
  #   type: "std_msgs::Float64"
  # - name: "/mushr/vesc/commands/motor/speed"
  #   type: "std_msgs::Float64"
  # - name: "/mushr/vesc/commands/motor/unsmoothed_speed"
  #   type: "std_msgs::Float64"
  # - name: "/mushr/vesc/commands/servo/position"
  #   type: "std_msgs::Float64"
  # - name: "/mushr/vesc/commands/servo/unsmoothed_position"
  #   type: "std_msgs::Float64"
  #   
  #   


