topics:
  - name: "/mushr/camera/rgb"
    type: "sensor_msgs::Image"
  - name: "/nodes/status/mujoco/change"
    type: "interface::NodeStatus"
  - name: "/nodes/status/mujoco/current"
    type: "interface::NodeStatus"
  - name: "/nodes/status/stela/change"
    type: "interface::NodeStatus"
  - name: "/nodes/status/stela/current"
    type: "interface::NodeStatus"
  - name: "/nodes/status/experiment_runner/change"
    type: "interface::NodeStatus"
  - name: "/nodes/status/experiment_runner/current"
    type: "interface::NodeStatus"
  - name: "/nodes/status/rosbag_recorder/change"
    type: "interface::NodeStatus"
  - name: "/nodes/status/rosbag_recorder/current"
    type: "interface::NodeStatus"
  - name: "/MJ_C0/info"
    type: "sensor_msgs::CameraInfo"
  - name: "/tf"
    type: "tf2_msgs::TFMessage"
  - name: "/tf_static"
    type: "tf2_msgs::TFMessage"
  - name: "/motion_planning/clock"
    type: "interface::PlannerClock"
  - name: "/environment_marker_array"
    type: "visualization_msgs::MarkerArray"
  - name: "/bounds"
    type: "visualization_msgs::Marker"
  - name: "/mushr/collision"
    type: "std_msgs::Bool"
  - name: "/stela/isam/status"
    type: "interface::StelaStatus"
  - name: "/stela/replanning/status"
    type: "interface::StelaStatus"
  - name: "/stela/estimation/tree"
    type: "prx_models::Tree"
  - name: "/mushr/sln/tree"
    type: "prx_models::Tree"
  - name: "/mushr/sln/tree_dbg"
    type: "prx_models::Tree"
  - name: "/stela/estimation/tree/controls"
    type: "interface::ControlsPlot"
  - name: "/mushr/sln/tree/controls"
    type: "interface::ControlsPlot"
  - name: "/stela/estimation/tree/edges/marker"
    type: "visualization_msgs::Marker"
  - name: "/stela/estimation/tree/nodes/marker"
    type: "visualization_msgs::Marker"
  - name: "/mushr/plan_stepper/control" 
    type: "ml4kp_bridge::SpacePoint"
  - name: "/stela/sbmp/control"
    type: "ml4kp_bridge::SpacePoint"
  - name: "/stela/sbmp/control_stamped" 
    type: "ml4kp_bridge::SpacePointStamped"
  - name: "/mushr/control" 
    type: "prx_models::MushrControl"
  - name: "/mushr/plan" 
    type: "prx_models::MushrPlan"
  - name: "/mushr/pose"
    type: "prx_models::MushrObservation"
  - name: "/mushr/sensordata"
    type: "interface::SensorDataStamped"
  - name: "/stela/sbmp/estimated_trajectory" 
    type: "ml4kp_bridge::StelaTrajectory"
  - name: "/mushr/reset" 
    type: "std_msgs::Empty"
  - name: "/mushr/sln/tree/edges/marker"
    type: "visualization_msgs::Marker"
  - name: "/mushr/sln/tree/nodes/marker"
    type: "visualization_msgs::Marker"
  - name: "/mushr/tree"
    type: "prx_models::Tree"
  - name: "/mushr/tree/edges/marker"
    type: "visualization_msgs::Marker"
  - name: "/mushr/tree/nodes/marker"
    type: "visualization_msgs::Marker"
  - name: "/kraft/status"
    type: "interface::ReplannerStatus"
  - name: "/mushr/sensordata/marker"
    type: "visualization_msgs::Marker"

