topics:
  # - name: "/desktop07/camera/rgb"
  #   type: "sensor_msgs::Image"
  # - name: "/robb/camera/rgb"
    # type: "sensor_msgs::Image"
  - name: "/desktop07/markers"
    type: "interface::StampedMarkers"
  - name: "/robb/markers"
    type: "interface::StampedMarkers"
  - name: "/mushr/ml4kp_traj"
    type: "ml4kp_bridge::TrajectoryStamped"
  - name: "/mushr/ml4kp_plan"
    type: "ml4kp_bridge::PlanStamped"
  - name: "/mushr/goal_pos"
    type: "geometry_msgs::Pose2D"
  - name: "/mushr/goal_radius"
    type: "std_msgs::Float64"
  # - name: "/tf"
  #   type: "tf2_msgs::TFMessage"
  # - name: "/tf_static"
  #   type: "tf2_msgs::TFMessage"
  - name: "/mushr/aruco_cTw/robot_pose"
    type: "geometry_msgs::PoseStamped"
  - name: "/mushr/vesc/commands/motor/current"
    type: "std_msgs::Float64"
  - name: "/mushr/vesc/commands/motor/brake"
    type: "std_msgs::Float64"
  - name: "/mushr/vesc/commands/motor/duty_cycle"
    type: "std_msgs::Float64"
  - name: "/mushr/vesc/commands/motor/position"
    type: "std_msgs::Float64"
  - name: "/mushr/vesc/commands/motor/speed"
    type: "std_msgs::Float64"
  - name: "/mushr/vesc/commands/motor/unsmoothed_speed"
    type: "std_msgs::Float64"
  - name: "/mushr/vesc/commands/servo/position"
    type: "std_msgs::Float64"
  - name: "/mushr/vesc/commands/servo/unsmoothed_position"
    type: "std_msgs::Float64"
  - name: "/stela/sbmp/sln_tree" 
    type: "prx_models::Tree"
  - name: "/stela/sbmp/tree"
    type: "prx_models::Tree"