float32 planned_duration
int32 iteration_count 
int32 total_nodes  
float32 cost_current_solution
float32 time_current_solution
int32 iters_current_solution

## Dirt-Specific
int32 random_edges_bnb
int32 random_edges_prunning
int32 random_edges_collision_check
int32 random_edges_final

int32 blossom_edges_bnb
int32 blossom_edges_prunning
int32 blossom_edges_collision_check
int32 blossom_edges_final

int32 solution_type

# int32 TREE_TRAJECTORY=0
# int32 WAVEFRONT=1
# int32 NONE=400