geometry:
  type: "SPHERE"
  parameters: [ 0.01 ]
# resolution: 0.5
resolution: 0.02
# environment: "environments/forest.yaml"
# environment_file: "environments/forest.yaml"
environment: "environments/boxes.yaml"
environment_file: "environments/boxes.yaml"
# environment: "environments/turns.yaml"
# environment_file: "environments/turns.yaml"
# environment: "environments/slip.yaml"
# environment_file: "environments/slip.yaml"
# environment: "environments/prx_lab_2.yaml"
# environment: "environments/movable.yaml"
# environment_file: "environments/movable.yaml"
directory: "${ML4KP_ROS}/data/sdfs/"