random_seed: 231192
# random_seed: 9080352
simulation_step: 0.1

environment: "environments/simple_obstacle.yaml"

bnb: true

visualize: true

checker_type: time
# checker_value: 7200
# checker_value: 3600
checker_value: 600
# checker_value: 120
# checker_value: 60
# checker_value: 30
# checker_value: 4
# cost_multiplier: 2.5
cost_multiplier: 1.0

max_edge_duration: 1.0

medial_axis:
  use: true
  rate: 0.1
  directory: "${ML4KP_ROS}/data/medial_axis/"
  # filename: "${ML4KP_ROS}/data/medial_axis/simple_obstacle.txt"
  # filename: "${ML4KP_ROS}/data/medial_axis/forest.txt"
  # filename: "${ML4KP_ROS}/data/medial_axis/warehouse.txt"
  resolution: 0.01
  geometry:
    parameters: [0.5]
