start_state:
  [1.0, 0.0, 1.57, 0.0, 0.0, 0.0]
goal:
  state:
    [1.0, 5.0, 1.57, 0.0, 0.0, 0.0]
  radius: 0.75
visualize: false
total_solutions: 1
# solution_type: "TREE_TRAJECTORY"
solution_type: "WAVEFRONT"
