bnb: false
use_replanning: true
control_steps:
  min: 2
  max: 8
blossom_number: 10
planning_cycle_duration: 1.0
use_pruning: false
use_contingency: false
profile: false
# output_path: "${ML4KP_ROS}/data/dirt"
output_path: "/tmp/"
# f_type: "f=g+h"
f_type: "f=h"
plan_safety_params:
  safe_min: 0.02
  safe_mul: 0.15
  safe_quad_mul: 0.0