name: "fg_ltv_sde"
path: "fg_ltv_sde"

vis_body: "body"

control_steps: 
  min: 5
  max: 15

start_state: [0,0,0,0]

goal:
  radius: 0.5
  state: [20,20,0,0]

state_space:
  lower_bound: [-5, -5, -1, -1]
  upper_bound: [25, 25, 1, 1]

control_space:
  lower_bound: [-0.1, -0.1]
  upper_bound: [0.1, 0.1]

parameter_space:
  values: [1, 0, 0, 0, 0, 0, 0, 0]