name: "mushrFG"
path: "mushrFG"

vis_body: "body"

control_steps: 
  min: 30
  max: 75

# start_state: [1,-0.5,1.5707963268,0] # obstacle_0
start_state: [0,0,1.5707963268,0] # simple_obstacle && forest
# start_state: [-3,-3,0,0]

goal:
  radius: 0.5
  state: [20,20,1.5707963268,0]
  # state: [1,5.5,1.5707963268,0]
  # state: [43.5,20,0,0]

state_space:
  # lower_bound: [-1, -1, -3.14159, -0.5]
  # upper_bound: [50, 25, 1, 1]
  # upper_bound: [50, 25, 0.5, 0.5]
  # upper_bound: [3, 8, 3.14159, 0.5]
  # upper_bound: [5, 10, 3.14159, 500] # obstacle_0
  lower_bound: [-5, -5, -3.14159, -500]
  upper_bound: [25, 25, 3.14159, 500]

control_space:
  lower_bound: [-0.5, -0.79]
  upper_bound: [ 0.5,  0.79]

parameter_space:
  values: [0.929102, 0.752216, 0.398495]
  # values: [0.01, 0.01, 0.01, 0.01, 1, 1, 1, 1]