state_space:
  bounds:
    -
      min: -3.14159
      max: +3.14159
    -
      min: -6.28318
      max: +6.28318
control_space:
  bounds:
    min: -0.6371781908344007
    max: +0.6371781908344007
parameter_space:
sensor_space:
  bounds:
    -
      min: -3.14159
      max: +3.14159
    -
      min: -6.28318
      max: +6.28318